services:
  node:
    container_name: ${APP_NAME}_node
    build:
      context: .
      dockerfile: ${DOCKER_SERVICES_PATH}/node/Dockerfile
      args:
        DOCKER_SERVICES_PATH: ${DOCKER_SERVICES_PATH}
    restart: unless-stopped
    tty: true
    volumes:
      - type: bind
        source: .
        target: /var/www/
    ports:
      - "${DOCKER_NODE_NETWORK_PORT}:80"
    networks:
      frontend_docker:
        ipv4_address: ${DOCKER_NODE_NETWORK_IP_ADDRESS}

networks:
  frontend_docker:
    name: frontend_docker
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_NETWORK_SUBNET}